language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install
  - npm install -g @angular/cli
script:
  - npm run build
deploy:
  provider: npm
  email: yhjang@satreci.com
  api_key: $NPM_TOKEN
  on:
    branch: master